/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PersonalFinanceTracker;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

import java.awt.*;
import java.util.List;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;

/**
 *
 * @author HP ElitePC
 */
public class BudgetvsActualPanel extends javax.swing.JPanel {

    private DefaultCategoryDataset dataset;
    private ChartPanel chartPanel;
    private String title;
    private int userId;
    private Database db;

    /**
     * Creates new form BudgetvsActualPanel
     */
      public BudgetvsActualPanel(int userId, String title, Database db) {
          
            this.userId = userId;
            this.title = title;
            this.db = db;
            setLayout(new BorderLayout());
            setBackground(Color.WHITE);

            dataset = new DefaultCategoryDataset();
            JFreeChart chart = ChartFactory.createBarChart(
                    title,
                    "Category",
                    "Amount",
                    dataset
            );

            // Get plot and renderer to adjust bar width
            CategoryPlot plot = chart.getCategoryPlot();
            BarRenderer renderer = (BarRenderer) plot.getRenderer();

            // Increase space between bars to make them thinner
            renderer.setItemMargin(0.3); 

            // Increase space between categories (groups of bars)
            plot.getDomainAxis().setCategoryMargin(0.3);  // default is ~0.2, increase for more space

            chartPanel = new ChartPanel(chart);
            add(chartPanel, BorderLayout.CENTER);

            updateChart(); // Initial load
        }

     
     
     
        
          public void updateChart() {
            dataset.clear();
            List<BudgetSummary> data = db.getBudgetVsActual(userId);
            for (BudgetSummary summary : data) {
                String category = summary.getCategory();
                dataset.addValue(summary.getBudget(), "Budget", category);
                dataset.addValue(summary.getActual(), "Actual", category);
                dataset.addValue(summary.getSavings(), "Savings", category);
            }

            chartPanel.getChart().setTitle(title + " (Current Month)");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
