/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package PersonalFinanceTracker;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author HP ElitePC
 */
public class LoginBox extends java.awt.Dialog {
     private CardLayout layout;
    private JPanel container;
    /**
     * Creates new form LoginBox
     */
    public LoginBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        ImageIcon icon = new ImageIcon("C:\\Users\\HP ElitePC\\Documents\\NetBeansProjects\\PerdonalFinanceTracker\\src\\resources\\pftlogo.jpg");
         setIconImage(icon.getImage());
        layout = new CardLayout();
        container = new JPanel(layout);

        // Add panels
        LoginPanel loginPanel = new LoginPanel(this);
        SignUpPanel signupPanel = new SignUpPanel(this); // create this class

        container.add(loginPanel, "login");
        container.add(signupPanel, "signup");
        
        add(container);
        layout.show(container, "login");
    }

    public void showSignUpPanel() {
        layout.show(container, "signup");
    }

    public void showLoginPanel() {
        layout.show(container, "login");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginBox dialog = new LoginBox(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
