/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PersonalFinanceTracker;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
/**
 *
 * @author HP ElitePC
 */
public class NotificationPanel extends javax.swing.JPanel {
     private JPanel notificationsContainer;
   private List<String> notifications;
    /**
     * Creates new form NotificationPanel
     */
    public NotificationPanel() {
        initComponents();
        
        setLayout(new BorderLayout());
        setPreferredSize(new Dimension(400, 100));
        setBackground(new Color(30, 30, 30)); // dark background or choose your own

        notifications = new ArrayList<>();

        JLabel titleLabel = new JLabel("Notifications");
        titleLabel.setForeground(Color.WHITE);
        titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 16));
        titleLabel.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

        add(titleLabel, BorderLayout.NORTH);

        // Scrollable panel for notifications
        notificationsContainer = new JPanel();
        notificationsContainer.setLayout(new BoxLayout(notificationsContainer, BoxLayout.Y_AXIS));
        notificationsContainer.setBackground(new Color(45, 45, 45)); 
//        notificationsContainer.setBackground(Color.WHITE);


        JScrollPane scrollPane = new JScrollPane(notificationsContainer);
        scrollPane.setBorder(null);
        scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        add(scrollPane, BorderLayout.CENTER);
    }
    
    
   public void addNotification(String message, Color foregroundColor) {
    notifications.add(message);

    JLabel notificationLabel = new JLabel("• " + message);
    notificationLabel.setForeground(foregroundColor != null ? foregroundColor : new Color(0, 204, 204)); // Default teal if null
    notificationLabel.setFont(new Font("Segoe UI", Font.ITALIC, 16));
    notificationLabel.setBorder(BorderFactory.createEmptyBorder(2, 10, 2, 10));

    notificationsContainer.add(notificationLabel);
    notificationsContainer.revalidate();
    notificationsContainer.repaint();
}

    
   
      public List<String> getNotifications() {
        return notifications;
    }

    public void clearNotifications() {
    notificationsContainer.removeAll();  // remove all notification labels
    notificationsContainer.revalidate();
    notificationsContainer.repaint();
    notifications.clear();  // clear the stored list as well
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
