/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package PersonalFinanceTracker;

import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author HP ElitePC
 */
public class UserProfileBox extends JDialog {

    /**
     * Creates new form UserProfileBox
     */
    public UserProfileBox(java.awt.Frame parent, int userId) {
        super(parent, "User Profile", true);
      
         ImageIcon icon = new ImageIcon("C:\\Users\\HP ElitePC\\Documents\\NetBeansProjects\\PerdonalFinanceTracker\\src\\resources\\pftlogo.jpg");
         setIconImage(icon.getImage());
         
        setSize(700, 550);
        setLocationRelativeTo(parent);

        UserProfilePanel profilePanel = new UserProfilePanel(userId);
        add(profilePanel);

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
     public static void main(String[] args) {
        // Simulating a logged-in user with ID = 1
        int userId = 1; // Replace with Session.userId if you have session handling

        SwingUtilities.invokeLater(() -> {
            UserProfileBox dialog = new UserProfileBox(null, userId);
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
